In [1]:
import numpy as np

## Addition

In [2]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [4]:
m1 + m2


array([[14, 20, 13],
       [-2,  3,  9]])

## Subtraction

In [5]:
m3 = np.array([[5,3],[-2,4]])
m3

array([[ 5,  3],
       [-2,  4]])

In [7]:
m4 = np.array([[7,-5],[3,8]])
m4

array([[ 7, -5],
       [ 3,  8]])

In [8]:
m3-m4

array([[-2,  8],
       [-5, -4]])

In [10]:
m5 = np.array([[22.33,-4.73],[-203.14,1200.02],[4.22,234.10]])
m6 = np.array([[133.13, 448.29],[-340.21,1.06],[30.41,424.99]])
m5-m6

array([[-110.8 , -453.02],
       [ 137.07, 1198.96],
       [ -26.19, -190.89]])

## Errors

In [11]:
err1 = np.array([1,2,3,4,5])
err2 = np.array([1,2,3])
err1 + err2

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

## Exceptions (addition with a scalar)

In [12]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [13]:
m1+1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [15]:
err1

array([1, 2, 3, 4, 5])

In [16]:
err1+1

array([2, 3, 4, 5, 6])