In [1]:
import numpy as np

# Dot Product

## Multiply 2 vectors

In [12]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

multiply 2 vectors = 2x1 + 8x(-7) + (-4)x3

In [6]:
np.dot(x,y)

-66

In [8]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])


multiply 2 vectors = 0x20 + 2x3 + 5x4 + 8x(-1)

In [9]:
np.dot(u,v)

18

# Scalar * Vector

In [10]:
x

array([ 2,  8, -4])

In [11]:
x*5

array([ 10,  40, -20])

# Matrix * Matrix

<b>Condition:</b> multiply an <b>m x n</b> with an <b>n x k</b> matrix

For example: we can multiply:

2x3 x 3x1 (3x2, 3x3, 3x...) matrix

5x7 x 7x1 (7x2, 7x3, 7x...) matrix

<b>Result:</b> When multiply an <b>m x n</b> with an <b>n x k</b> matrix, the output is an <b>m x k </b> matrix

Ex: 

[2x3] x [3x6] = [2x6]

[100x300] x [300x3] = [100x3]

Method: 

[0,0] = sum(row(0) x col(0)) 

[0,1] = sum(row(0) x col(1))

...

In [14]:
m1 = np.array([[5,12,6],[-3,0,14]])
m2 = np.array([[2,-1],[8,0],[3,0]])
np.dot(m1,m2)

array([[124,  -5],
       [ 36,   3]])

## Example 2:

In [15]:
C = np.array([[-12,5,-5,1,6],[6,-2,0,0,3],[10,2,0,8,0],[9,-4,8,3,6]])
D = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])
np.dot(C,D)

array([[-71, -48],
       [  2, -25],
       [132,  14],
       [ 23, -51]])

-71