In [1]:
import numpy as np


## Creating a Matrix

Matrix is a np.array and is a collection of vectors

In [4]:
m1 = np.array([[5,12,-6], [-3, 0,14]])
m1

array([[ 5, 12, -6],
       [-3,  0, 14]])

In [5]:
m2 = np.array([[9,8,7], [1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

## Creating Tensor 

Tensor is a collection of matrices

In [7]:
tensor = np.array([m1,m2])
tensor


array([[[ 5, 12, -6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [9]:
tensor.shape

(2, 2, 3)

It is a 2x2x3 object => means it contains 2 matrices, and each one is a 2x3 matrix