In [1]:
import numpy as np

# Transposing matrices

In [2]:
A = np.array([[5,12,6],[-3,-0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [6]:
B = np.array([[5,3],[2,4]])
B

array([[5, 3],
       [2, 4]])

In [7]:
B.T

array([[5, 2],
       [3, 4]])

In [8]:
C = np.array([[4,-5],[8,12],[-2,-3],[-9,42323]])
C

array([[    4,    -5],
       [    8,    12],
       [   -2,    -3],
       [   -9, 42323]])

In [9]:
C.T

array([[    4,     8,    -2,    -9],
       [   -5,    12,    -3, 42323]])

# Transposing vectors

In [13]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [14]:
x.shape

(3,)

In [15]:
x.T

array([1, 2, 3])

In [16]:
x.shape

(3,)

In Python, 1D arrays don't really get transposed

If I reshape it into a 3x1 matrix or a 2D array, I will be able to transpose it.

In [17]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [18]:
x_reshaped.T

array([[1],
       [2],
       [3]])