# Train Test Split

## Import relevant librabries

In [5]:
import numpy as np
from sklearn.model_selection import train_test_split

## Generate some data we are going to split

In [7]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [9]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

## Split the data

In [11]:
train_test_split(a)

[array([ 85,  82,  46,  96,  20,   6,  32,  91,  57,  50,  17,  31,  21,
         16,  41,  80,  75,  27,  98,  40,  52,  37,  33,  18,  11,  99,
         88,  38,   3,  36,   1,  42,  39,  51,  29,  30,   9,  13,  45,
         55,  10,  19,  70,   8,  61,   5,  12,  74,  48,  78,  43,  22,
         90,  58,  35,  15,  53,  64,  60,  49,  65,  72,  79,  63,  77,
         84,  97,  71,  95,   2,  83, 100,  62,  25,  93]),
 array([ 7, 14, 76, 94, 56, 23, 86, 28, 44, 68, 92, 34, 26, 47, 24, 73, 59,
        69, 81, 89, 67, 54, 66, 87,  4])]

In [34]:
a_train, a_test, b_train, b_test = train_test_split(a,b, test_size=0.2, random_state=42)

## Explore the result

In [35]:
a_train.shape, a_test.shape

((80,), (20,))

In [36]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [37]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])